/* Typescript generated with NSwagStudio (UI Product, can be automated via command line interface) */
/* See ConferenceCast-MediaLibrary.nswag for current NSwag settings in client-admin root           */

/* tslint:disable */
/* eslint-disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.2.2.0 (NJsonSchema v10.1.4.0 (Newtonsoft.Json v11.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

export interface ConferenceElement {
    FolderPath?: string | undefined;
    FolderPath2?: string | undefined;
    ForeignDBKey?: string | undefined;
    ID: number;
    Index: number;
    LastChangeTime: Date;
    MiscAssets?: MiscAsset[] | undefined;
    MiscData?: string | undefined;
    ThumbnailURL?: string | undefined;
    Title?: string | undefined;
}

export interface Presentation extends ConferenceElement {
    Abstracts?: Abstract[] | undefined;
    AuthorBlock?: string | undefined;
    CaptionFlags: CaptionFlags;
    CaptionURLs?: string[] | undefined;
    ConferenceID: number;
    FeaturedImage?: string | undefined;
    Flags: PresentationFlags;
    HitCount: number;
    LengthSeconds: number;
    Location?: string | undefined;
    Media?: Media[] | undefined;
    MediaFlags: MediaFlags;
    ScheduledDate: Date;
    SessionID: number;
    Speakers?: Speaker[] | undefined;
}

export interface PresentationEx extends Presentation {
    ConferenceFlags: ConferenceFlags;
    ConferenceForeignDBKey?: string | undefined;
    ConferenceIndex: number;
    ConferenceMiscData?: string | undefined;
    ConferenceShortTitle?: string | undefined;
    ConferenceTitle?: string | undefined;
    SessionFlags: SessionFlags;
    SessionForeignDBKey?: string | undefined;
    SessionIndex: number;
    SessionMiscData?: string | undefined;
    SessionTitle?: string | undefined;
    SessionType: SessionTypeFlags;
    SessionTypeText?: string | undefined;
    StoreProductIDs?: string | undefined;
    SubscriptionURL?: string | undefined;
    Text?: string | undefined;
    TrackFlags: TrackFlags;
    TrackForeignDBKey?: string | undefined;
    TrackID: number;
    TrackIndex: number;
    TrackMiscData?: string | undefined;
    TrackTitle?: string | undefined;
}

export enum ConferenceFlags {
    None = 1,
    IsInProgress = 2,
    RequiresSubscription = 4,
    Pending = 8,
    AstuteMediaStoreProduct = 16,
    SubscriptionURL_IsMessage = 32,
    IsQC = 64,
    HideMobile = 128,
    HideMP3s = 256,
    HidePDFs = 512,
    SkipTracks = 1024,
    RequiresLogin = 2048,
    UserDefined = 4096,
    UserDefined_Hidden = 8192,
    Hidden = 16384,
    HasVoucherCodes = 32768,
    VouchersRequireAttendance = 65536,
    HasIndividualSubProductsInStore = 131072,
    SessionsAreProducts = 262144,
    ProductPlaceholder = 524288,
    IsLive = 1048576,
    IsCME = 2097152,
    All = 4194304,
}

export enum SessionFlags {
    None = 1,
    Sponsored = 2,
    IsQC = 4,
    IsFree = 8,
    RequiresLogin = 16,
    UserDefined = 32,
    UserDefined_Hidden = 64,
    Hidden = 128,
    NotDeployed = 256,
    IsProduct = 512,
    IsLive = 1024,
    IsCME = 2048,
    AllButHidden = 4096,
    All = 8192,
}

export enum SessionTypeFlags {
    None = 1,
    Discussion = 2,
    Education = 4,
    OralPresentation = 8,
    Poster = 16,
}

export enum TrackFlags {
    None = 1,
    Pathway = 2,
    UserDefined = 4,
    UserDefined_Hidden = 8,
    Hidden = 16,
}

export interface Abstract {
    AbstractID: number;
    AbstractIndex: number;
    Data?: string | undefined;
    ForeignDBKey?: string | undefined;
    Identifier?: string | undefined;
    PresentationID: number;
}

export enum CaptionFlags {
    None = 1,
    Arabic = 2,
    English = 4,
    French = 8,
    German = 16,
    Hindi = 32,
    Italian = 64,
    Japanese = 128,
    Korean = 256,
    Mandarin = 512,
    Portugese = 1024,
    Punjabi = 2048,
    Russian = 4096,
    Spanish = 8192,
}

export enum PresentationFlags {
    None = 1,
    NotGiven = 2,
    NotPermitted = 4,
    PermissionPending = 8,
    IsQC = 16,
    IsFree = 32,
    RequiresLogin = 64,
    UserDefined = 128,
    UserDefined_Hidden = 256,
    Hidden = 512,
    NotDeployed = 1024,
    IsLive = 2048,
    AllButHiddenAndNotGivenPermitted = 4096,
}

export interface Media {
    AssetsXML_URL?: string | undefined;
    MediaURL?: string | undefined;
    SecondaryURL?: string | undefined;
    Type: MediaTypeFlags;
}

export enum MediaTypeFlags {
    None = 1,
    Slides = 2,
    Audio = 4,
    SynchronizedAudioAndSlides = 8,
    WMV = 16,
    MP4_Progressive = 32,
    MP4_HLS = 64,
    Uses_ASX = 128,
    ZoomableSlides = 256,
    PDF_Slides = 512,
}

export enum MediaFlags {
    None = 1,
    SubmittedSlides = 2,
    CapturedSlides = 4,
    CapturedThumbs = 8,
    MP3 = 16,
    WMV = 32,
    FLV = 64,
    MP4 = 128,
    H264 = 256,
    MP4_MultiBitRate = 512,
    PDF_Slides = 1024,
    SlidesAndAudioAreSynchronized = 2048,
    ZoomableSlides = 4096,
    MISC = 8192,
    Pending = 16384,
    All = 32768,
}

export interface Speaker {
    Flags: SpeakerFlags;
    FirstName?: string | undefined;
    ForeignDBKey?: string | undefined;
    ImageURL?: string | undefined;
    MiddleName?: string | undefined;
    LastName?: string | undefined;
    EmailAddress?: string | undefined;
    Institution?: string | undefined;
    FullName?: string | undefined;
    Role: Role;
    RoleText?: string | undefined;
    SpeakerID: number;
    SpeakerIndex: number;
    SpeakerText?: string | undefined;
    Suffix?: string | undefined;
}

export enum SpeakerFlags {
    None = 1,
    DoNotEmail = 2,
}

export enum Role {
    None = 0,
    Speaker = 1,
    Speaker_Chair = 2,
}

export interface MiscAsset {
    Data?: string | undefined;
    AssetID: number;
    AssetIndex: number;
    MappingID: number;
    Text?: string | undefined;
    Type: AssetType;
}

export enum AssetType {
    None = 1,
    HTML = 2,
    HTML_Link = 4,
    Image_Link = 8,
    PDF_Link = 16,
    Text = 32,
    Speaker = 64,
    CME = 128,
    Sponsor = 256,
}

export interface Track extends ConferenceElement {
    ConferenceID: number;
    Flags: TrackFlags;
}

export interface TrackTree extends Track {
    SessionMaps?: TrackSessionMap[] | undefined;
}

export interface TrackSessionMap {
    SessionID: number;
    TrackPriorityPerSessionIndex: number;
}

export interface PresentationTree extends Presentation {
}

export interface Session extends ConferenceElement {
    AssociatedTrackID: number;
    ConferenceID: number;
    Flags: SessionFlags;
    Type: SessionTypeFlags;
    TypeText?: string | undefined;
}

export interface SessionTree extends Session {
    Presentations?: PresentationTree[] | undefined;
}

export interface SessionEx extends Session {
    ConferenceFlags: ConferenceFlags;
    ConferenceForeignDBKey?: string | undefined;
    ConferenceIndex: number;
    ConferenceMiscData?: string | undefined;
    ConferenceShortTitle?: string | undefined;
    ConferenceTitle?: string | undefined;
    StoreProductIDs?: string | undefined;
    SubscriptionURL?: string | undefined;
    TrackFlags: TrackFlags;
    TrackForeignDBKey?: string | undefined;
    TrackID: number;
    TrackIndex: number;
    TrackMiscData?: string | undefined;
    TrackTitle?: string | undefined;
}

export interface Conference extends ConferenceElement {
    BannerURL?: string | undefined;
    Date: Date;
    Description?: string | undefined;
    Flags: ConferenceFlags;
    LengthDays: number;
    Location?: string | undefined;
    Marketing?: string | undefined;
    ShortTitle?: string | undefined;
    StoreProductIDs?: string | undefined;
    SubscriptionURL?: string | undefined;
    Timezone?: string | undefined;
}

export interface ConferenceTree extends Conference {
    Sessions?: SessionTree[] | undefined;
    Tracks?: TrackTree[] | undefined;
}
